CC=gcc
CFLAGS=-g -std=c99 -Wall
#LDFLAGS=-lm

test3:
	./part3 "only one parameter"
	./part3 "biggest parameter" "at" "start"
	./part3 "biggest" "parameter" "at" "end" "very very very big parameter"
	./part3 "answer" "somewhere" "in" "the" "middle"
	./part3 "two" "strings" "the" "same" "length" "ha ha !"
	./part3 #no parameters

test4:
	./part4 -c 110
	./part4 -f 230
	./part4 -f 1.54
	./part4 -c -98.2
	./part4 -c 0
	./part4 -c 100

	./part4 -c -274
	./part4 -f -459.67
	./part4 -459.67
	./part4 -f
	./part4
	./part4 -12 -f

test5:
	./part5 part5test1.txt
	./part5 part5test2.txt
	./part5 part5test3.txt
	./part5 part5test4.txt
